---

- name: Tear down existing services
  docker_compose:
    project_src: /opt/siem
    state: absent

- name: Copy Docker Compose files
  copy:
    src: files/{{ item }}
    dest: /opt/siem/{{ item }}
    loop:
    - docker-compose.yml
    - docker-compose.prod.yml

- name: Deploy Docker Compose stack
  docker_compose:
    project_src: /opt/siem
    files:
    - docker-compose.yml
    - docker-compose.prod.yml

- name: Create and start services
  docker_compose:
    project_src: flask
    register: output

- debug:
    var: output

- name: Run `docker-compose up` again
  docker_compose:
    project_src: flask
    build: no
    register: output

- debug:
    var: output

- assert:
    that: "not output.changed "
